### ISSUE TITLE
prevents topic from rendering

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-github-embed#27]
```
2023-01-18T03:09:15.963Z [4567/17960] - error: GET /topic/810/nodebb-plugin-blog-comments-blog-commenting-engine-ghost-wordpress-widget/70
StatusCodeError: 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/issues#get-an-issue"}
    at new StatusCodeError (D:\github\NodeBB\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\github\NodeBB\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\github\NodeBB\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\github\NodeBB\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (D:\github\NodeBB\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (D:\github\NodeBB\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
```

**Comment by julianlam** [comment]
How did you trigger this error :thinking:

**Comment by barisusakli** [comment]
No idea 😆

**Comment by julianlam** [comment]
Oh, perhaps this is why gh-embed was disabled on community? :smile:
